name             'bitcoind'
maintainer       'Joshua Estes'
maintainer_email 'Joshua@dSpaceLabs.com'
license          'MIT'
description      'Installs/Configures bitcoind'
long_description 'Installs/Configures bitcoind'
version          '0.1.1'
