name             'bitcoind'
version          '0.3.0'
maintainer       'Joshua Estes'
maintainer_email 'Joshua@dSpaceLabs.com'
license          'MIT'
description      'Installs and configures a bitcoind node'
supports         'ubuntu'
#issues_url       'https://github.com/nbobtc/bitcoind-cookbook/issues'
#source_url       'https://github.com/nbobtc/bitcoind-cookbook'
